//
// Created by Ion Agorria on 15/9/19
//
#ifndef OPENE2140_ENERGY_COMPONENT_H
#define OPENE2140_ENERGY_COMPONENT_H

#include "component.h"

class Entity;

/**
 * Component that provides power usage and generation across entities
 */
class EnergyComponent {
CLASS_COMPONENT(Entity, EnergyComponent)
protected:
    /** The energy generated by this entity */
    entity_energy_t energyGeneration = 0;

    /** The power requirement for this entity */
    entity_energy_t energyRequirement = 0;

    /** True if the player has enough energy to satisfy this entity power requirements */
    bool energySatisfied = false;
public:
};


#endif //OPENE2140_ENERGY_COMPONENT_H
