//
// Created by Ion Agorria on 2/06/19
//
#ifndef OPENE2140_CONSTANTS_H
#define OPENE2140_CONSTANTS_H

#define MONEY_PER_CONTAINER 200
#define CAMERA_SPEED 10

#define ENTITY_KIND_OBJECT 0
#define ENTITY_KIND_UNIT 1
#define ENTITY_KIND_BUILDING 2
#define ENTITY_KIND_PROJECTILE 3
#define ENTITY_KIND_EXPLOSION 4

#endif //OPENE2140_CONSTANTS_H
